deafult:
	g++ -std=c++11 -o main main.cpp

run:
	g++ -std=c++11 -o main main.cpp
	main.exe < test1.txt

graph:
	g++ -std=c++11 -o graphs2 graphs2.cpp
	graphs2.exe

graph3:
	g++ -std=c++11 -o graphs3 graphs3.cpp
	graphs3.exe

algo:
	g++ -std=c++11 -o algo graphAlgo.cpp
	algo.exe
matrix:
	g++ -std=c++11 -o matrix matrix.cpp
	matrix.exe < test.txt
prim:
	g++ -std=c++11 -o prim prim.cpp
	prim.exe < input.txt
kruskal:
	g++ -std=c++11 -o kruskal kruskal.cpp
	kruskal.exe