default:
	g++ -std=c++11 MemoryManager.cpp main.cpp -g -o main
	./main

win:
	g++ -std=c++11 -g MemoryManager.cpp main.cpp -g -o main
	main.exe

cli:
	g++ -std=c++11 -g MemoryManager.cpp CommandLineTest.cpp -g -o cli
	cli.exe
