#g++ -0 bin/program src/*.cpp exmaple from Professor
build:
	g++ -std=c++11 src//main.cpp src//ImageProcessing.cpp -o project2.out -Wall -w -Wwrite-strings

run:
	project2.out

clean:
	del project2.exe
	del project2.out
	del *.tga
	del output\\*.tga