CPP=clang++
FLAGS= -o game -g -Wall -std=c++11
LIB= lib/libraylib.a
FRAMEWORK= -framework CoreVideo -framework IOkit -framework Cocoa -framework GLUT -framework OpenGL

default:
	cl -Zi main.c 

hw1:
	cl -Zi hw1/main.c 

run:
	main.exe